on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        version: "^1.14.1"
    - run: ./ui_test.sh
      name: Run UI tests
